[project]

name = "testax"
version = "0.1.0"
dependencies = [
    "jax",
]

[tool.coverage.report]
exclude_also = [
    "raise NotImplementedError",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
